In [1]:
import numpy as np
import random

In [10]:
gamma = 0.8
Q = np.zeros([6,6])
R = np.array([[-1,-1,-1,-1, 0, -1],
              [-1,-1,-1, 0,-1,100],
              [-1,-1,-1, 0,-1, -1],
              [-1, 0, 0,-1, 0, -1],
              [ 0,-1,-1, 0,-1,100],
              [-1, 0,-1,-1, 0,100]])

for episode in range(0,50):
    initial_state = random.randint(0,5)
    current_state = initial_state
    flag = 0
    while flag == 0 or current_state != 5:
        flag = 1
        current_state_aggregate = {}
        next_state_aggregate = {}
        for index, value in enumerate(R[current_state]):
            if value != -1:
                current_state_aggregate[index] = value
        next_state = random.choice(list(current_state_aggregate.keys()))
        for index_, value_ in enumerate(R[next_state]):
            if value_ != -1:
                next_state_aggregate[index_] = value_
        Q[current_state,next_state] = R[current_state,next_state] + gamma*max(Q[next_state,list(next_state_aggregate.keys())])
        current_state = next_state
        
    print(Q.astype('int32'))
    print("\n")

[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0   0   0  80   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0   0   0  80   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]
 [  0  80   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0   0   0  80   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]
 [  0  80   0   0   0   0]
 [  0   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0  64   0   0]
 [  0  80  51   0  80   0]
 [ 64   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0  64   0   0]
 [  0  80  51   0  80   0]
 [ 64   0   0   0   0 100]
 [  0   0   0   0   0   0]]


[[  0   0 